# TravisCI configuration for Slic3r - https://slic3r.org
# 
# We build Linux and macOS versions on TravisCI, both the main program
# (perl/C++) and the pure C++ one.
# 
# Each job performs the following steps:
# - install dependencies (cached across builds)
# - build
# - test
# - package
# - deploy to dl.slic3r.org

language: generic
dist: trusty

before_install:
    - sh package/common/travis-decrypt-key
    - export SLIC3R_GIT_VERSION=$(git rev-parse HEAD)

script:
    - if [[ "${TRAVIS_OS_NAME}" == "linux" && "$BUILD_PL" == true  ]]; then ./package/linux/travis-build-main.sh; fi
    - if [[ "${TRAVIS_OS_NAME}" == "linux" && "$BUILD_PL" == false ]]; then ./package/linux/travis-build-cpp.sh; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx"   && "$BUILD_PL" == true  ]]; then ./package/osx/travis-build-main.sh; fi
    - if [[ "${TRAVIS_OS_NAME}" == "osx"   && "$BUILD_PL" == false ]]; then ./package/osx/travis-build-cpp.sh; fi

branches:
  only:
  - master
  - cppgui
  - osxbuild

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - gcc-7
    - g++-4.9
    - gcc-4.9
    - libgtk2.0-0 
    - libgtk2.0-dev
    - freeglut3
    - cmake
    - wx3.0-headers
    - libwxgtk3.0-dev
    - wx-common
  ssh_known_hosts: dl.slic3r.org

matrix:
    include:
        - os: linux
          env:
            - BUILD_PL=true
            - CACHE=$HOME/cache
          cache:
            directories:
              - $HOME/cache
              - local-lib
          after_success:
            - package/linux/travis-deploy-main.sh

        - os: linux
          env: 
            - BUILD_PL=false
            - CACHE=$HOME/cache
          cache:
            apt: true
            directories:
              - $HOME/cache
          after_success:
            - package/linux/travis-deploy-cpp.sh

        - os: osx
          osx_image: xcode9.4
          env:
            - BUILD_PL=true
          cache:
            directories:
              - /usr/local/Homebrew
              - $HOME/Library/Caches/Homebrew
              - local-lib
          after_success:
            - package/osx/travis-deploy-main.sh

        - os: osx
          osx_image: xcode9.4
          env:
            - BUILD_PL=false
            - CACHE=$HOME/cache
          cache:
            ccache: true
            directories:
              - /usr/local/Homebrew
              - $HOME/cache
              - $HOME/Library/Caches/Homebrew

env:
  global:
  - secure: eEVRZNMv7FM6jrOU9iAFkDhWxFQ1WtHBEaObImcvtFUxy6vWSt3ehFFeTRouj3uHQAnbvUzziDyvPPm8/95alv5g/du8ML6YzzqKBKfazM0xQ7SF6R2DQL8lfFIp+RSV7T02byEP1f1g7Zva7xH9szIlDcSfU0pXW4KWbkBFMd8=
  - secure: gj338h+qHGccTD/VQFmEJkqdg2McIe2pO0iZ4Ae9BvY5vxkIML4BpoYZQXQTqiAOETnUjlcknY9lx0hI/PfkDD9MSJc5BC/3fMYRCu3SgAclEwklWf9vvtodUeT69mtnZuw1zze1nTbExuOw2mepbqFjxKKMl+9l5oCz4O54fXU=

notifications:
  irc:
    channels:
    - chat.freenode.net#slic3r
    on_success: change
    on_failure: always
    use_notice: true
