language: perl
install:
    - export LDLOADLIBS=-lstdc++
    - export BOOST_DIR=$HOME/boost_1_63_0
    - export SLIC3R_STATIC=1
    - export CXX=g++-4.9
    - export CC=g++-4.9
script: 
    - bash package/linux/travis-setup.sh
    - perlbrew switch slic3r-perl
    - perl ./Build.PL
after_success:
    - deploy
branches:
  only:
    - master
    - xsgui
cache:
  apt: true
  directories:
    - local-lib
    - $HOME/cache
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9

notifications:
  irc:
    channels:
      - "chat.freenode.net#slic3r"
    on_success: change
    on_failure: always
    use_notice: true

sudo: true
dist: trusty
